// <auto-generated />
namespace TrashCollection.Migrations.TCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedrouteview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedrouteview));
        
        string IMigrationMetadata.Id
        {
            get { return "201802260004088_removed routeview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
